// nav_icons.h — Cross-platform nav-bar icon rendering via embedded
// Phosphor Icons (MIT) alpha masks.
//
// Original Linux-only motivation: SWELL's CreateFont on Linux resolves an
// empty font family to fontconfig's default (Noto Sans Regular on
// Ubuntu 24.04), which lacks the seven Unicode codepoints the nav-bar
// glyph path used (U+2302 ⌂, U+2295 ⊕, U+2315 ⌕, U+2B07 ⬇, U+2261 ≡,
// U+2699 ⚙, U+2665 ♥); SWELL performs no per-glyph fallback, so the
// buttons rendered as tofu boxes. macOS SF Pro and Windows Segoe UI
// covered the codepoints, masking the gap on those platforms.
//
// v2.0.2 unifies the path: every platform draws the same Phosphor
// pictograms by compositing the embedded alpha against the requested
// background + tint color and blitting via SWELL CreateBitmap +
// StretchBlt. Side benefits: no per-glyph fontPx / yOffset tuning table,
// no per-platform anti-alias differences from the system font rasterizer,
// and the bar renders identically across macOS / Win / Linux.
//
// Raw alpha data lives in cpp/resources/nav_icons.gen.cpp (generated by
// cpp/resources/icons/gen_nav_icons.py from the 7 SVG sources in
// cpp/resources/icons/phosphor-regular/). Regenerate after touching any
// SVG.
#pragma once

#include "platform.h"

namespace NavIcons {

// Returns the raw alpha mask for `buttonId` at the requested scale
// (0 = 26 px, 1 = 52 px). `*outW` and `*outH` receive the bitmap
// dimensions. Returns nullptr / 0×0 for an unknown buttonId.
// Defined in cpp/resources/nav_icons.gen.cpp.
const unsigned char* GetIconAlpha(int buttonId, int scale2x,
                                  int* outW, int* outH);

// Composite the icon for `buttonId` over `bgColor` tinted to `iconColor`
// and blit into `hdc` filling `r`. Anti-aliased edges via per-pixel alpha
// blend. No-op for unknown buttonId or empty rect.
void DrawIcon(HDC hdc, int buttonId, const RECT& r,
              COLORREF bgColor, COLORREF iconColor);

}  // namespace NavIcons
