#!/usr/bin/env python3
"""Convert Phosphor SVGs to embedded raw-alpha byte arrays for nav_icons.gen.cpp.

Source: ./phosphor-regular/*.svg  (Phosphor Icons, MIT-licensed)
Output: ../nav_icons.gen.cpp

Each icon is rasterized to RGBA at 1x (26 px, button size) and 2x (52 px,
HiDPI). Only the alpha channel is emitted — the runtime pre-composes against
the requested button bg and tint color before blitting via SWELL's
CreateBitmap + StretchBlt, so source RGB is discarded.

Raw alpha avoids pulling in libpng (~100 KB compiled) just to decode 7 tiny
icons; the cost is ~24 KB of icon data instead of ~9 KB.

Regenerate after touching any SVG:  python3 gen_nav_icons.py
"""

import os
import subprocess
import tempfile

# Backend auto-detect — PyGI on Linux desktop (preinstalled), rsvg-convert
# + Pillow on macOS/Win where PyGI is awkward to install but librsvg is
# easily available via brew/winget. Output is bit-equivalent — both go
# through librsvg under the hood. PIL/Pillow provides RGBA extraction.
try:
    import gi
    gi.require_version('Rsvg', '2.0')
    gi.require_version('GdkPixbuf', '2.0')
    from gi.repository import Rsvg, GdkPixbuf  # noqa: F401, E402
    BACKEND = 'pygi'
except (ImportError, ValueError):
    from PIL import Image
    BACKEND = 'rsvg-convert'

# Order must match NavBar::ButtonId in cpp/src/nav_bar.h.
ICONS = [
    (0, 'house-simple'),        # BTN_HOME
    (1, 'arrows-in-cardinal'),  # BTN_DRAG
    (2, 'magnifying-glass'),    # BTN_SWITCH
    (3, 'floppy-disk'),         # BTN_SAVE
    (4, 'folder-open'),         # BTN_LOAD
    (5, 'gear'),                # BTN_SETTINGS
    (6, 'heart'),               # BTN_SUPPORT
]
SIZES = [26, 52]  # 1x = BUTTON_SIZE, 2x = HiDPI

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(HERE, 'phosphor-regular')
OUT_PATH = os.path.normpath(os.path.join(HERE, '..', 'nav_icons.gen.cpp'))


def render_svg_to_alpha_pygi(svg_path, size_px):
    pb = Rsvg.pixbuf_from_file_at_size(svg_path, size_px, size_px)
    w = pb.get_width()
    h = pb.get_height()
    if not pb.get_has_alpha() or pb.get_n_channels() != 4:
        raise RuntimeError(
            f'{svg_path}: expected 4-channel RGBA pixbuf, got '
            f'{pb.get_n_channels()} channels, alpha={pb.get_has_alpha()}')
    raw = bytes(pb.get_pixels())
    rowstride = pb.get_rowstride()
    out = bytearray(w * h)
    for y in range(h):
        row = raw[y * rowstride:y * rowstride + w * 4]
        for x in range(w):
            out[y * w + x] = row[x * 4 + 3]  # alpha channel
    return w, h, bytes(out)


def render_svg_to_alpha_rsvg_convert(svg_path, size_px):
    with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as f:
        tmp_png = f.name
    try:
        subprocess.run(
            ['rsvg-convert',
             '-w', str(size_px), '-h', str(size_px),
             svg_path, '-o', tmp_png],
            check=True, capture_output=True)
        img = Image.open(tmp_png).convert('RGBA')
        w, h = img.size
        alpha = img.split()[3].tobytes()
        return w, h, alpha
    finally:
        try:
            os.unlink(tmp_png)
        except OSError:
            pass


def render_svg_to_alpha(svg_path, size_px):
    if BACKEND == 'pygi':
        return render_svg_to_alpha_pygi(svg_path, size_px)
    return render_svg_to_alpha_rsvg_convert(svg_path, size_px)


def fmt_array(sym, blob):
    lines = [f'static const unsigned char {sym}[{len(blob)}] = {{']
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        lines.append('  ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',')
    lines.append('};')
    return '\n'.join(lines)


def main():
    parts = [
        '// nav_icons.gen.cpp — GENERATED by cpp/resources/icons/gen_nav_icons.py.',
        '// DO NOT EDIT BY HAND. Regenerate after touching SVG sources:',
        '//   python3 cpp/resources/icons/gen_nav_icons.py',
        '//',
        '// Source: Phosphor Icons (MIT) — https://phosphoricons.com',
        '// Raw 8-bit alpha masks at 1x (26 px) and 2x (52 px). The runtime',
        '// pre-composes the alpha against the requested bg + tint color and',
        '// blits via SWELL CreateBitmap + StretchBlt — cross-platform path.',
        '',
        '#include "nav_icons.h"',
        '',
        'namespace NavIcons {',
        'namespace {',
        '',
    ]

    entries = []
    for btn_id, name in ICONS:
        for size in SIZES:
            scale_tag = '1x' if size == 26 else '2x'
            sym = 'k' + name.replace('-', '_') + '_' + scale_tag
            w, h, alpha = render_svg_to_alpha(
                os.path.join(SRC_DIR, name + '.svg'), size)
            parts.append(fmt_array(sym, alpha))
            parts.append('')
            entries.append((btn_id, scale_tag, sym, w, h, len(alpha)))

    parts.append('}  // namespace (anon)')
    parts.append('')
    parts.append('struct Blob { const unsigned char* data; int w; int h; };')
    parts.append('// kTable[buttonId][scale] — scale 0 = 1x, 1 = 2x.')
    parts.append('static const Blob kTable[7][2] = {')
    by_btn = {}
    for btn, tag, sym, w, h, n in entries:
        by_btn.setdefault(btn, {})[tag] = (sym, w, h)
    for b in range(7):
        a = by_btn[b]['1x']
        c = by_btn[b]['2x']
        parts.append(f'  {{ {{ {a[0]}, {a[1]}, {a[2]} }}, {{ {c[0]}, {c[1]}, {c[2]} }} }},')
    parts.append('};')
    parts.append('')
    parts.append('const unsigned char* GetIconAlpha(int buttonId, int scale2x, int* outW, int* outH)')
    parts.append('{')
    parts.append('  if (buttonId < 0 || buttonId >= 7) {')
    parts.append('    if (outW) *outW = 0;')
    parts.append('    if (outH) *outH = 0;')
    parts.append('    return nullptr;')
    parts.append('  }')
    parts.append('  const Blob& b = kTable[buttonId][scale2x ? 1 : 0];')
    parts.append('  if (outW) *outW = b.w;')
    parts.append('  if (outH) *outH = b.h;')
    parts.append('  return b.data;')
    parts.append('}')
    parts.append('')
    parts.append('}  // namespace NavIcons')
    parts.append('')

    with open(OUT_PATH, 'w') as f:
        f.write('\n'.join(parts))
    total = sum(n for *_, n in entries)
    print(f'Wrote {OUT_PATH}')
    print(f'  backend: {BACKEND}')
    print(f'  {len(entries)} icons, {total} bytes of alpha data total')


if __name__ == '__main__':
    main()
